"""
AccessCode model for institutional token-based access.

Supports correctional facilities and other environments where email
onboarding isn't possible. Codes are generated by tenant admins and
distributed (e.g. printed) to learners.
"""
import secrets
import string
from datetime import datetime, timezone

from sqlalchemy import (
    Column, Integer, String, DateTime, Boolean, JSON, ForeignKey,
)
from sqlalchemy.orm import relationship

from app.database import Base

# Characters for access codes — uppercase + digits, no ambiguous chars (0/O, 1/I/L)
CODE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
CODE_LENGTH = 8


def generate_code() -> str:
    """Generate a cryptographically random access code."""
    return "".join(secrets.choice(CODE_ALPHABET) for _ in range(CODE_LENGTH))


class AccessCode(Base):
    """
    A redeemable access code tied to a tenant.

    Correctional facility workflow:
    1. Tenant admin calls POST /tenants/{slug}/access-codes with count=200
    2. API generates 200 unique codes
    3. Facility staff print codes on cards
    4. Learner enters code on FSA → POST /access/redeem
    5. System creates anonymous user, grants entitlement, returns JWT
    """
    __tablename__ = "access_codes"

    id = Column(Integer, primary_key=True, index=True)
    tenant_id = Column(Integer, ForeignKey("tenants.id"), nullable=False, index=True)
    code = Column(String(16), unique=True, index=True, nullable=False, default=generate_code)

    # Usage limits
    max_uses = Column(Integer, nullable=False, default=1)
    times_used = Column(Integer, nullable=False, default=0)

    # When max_uses=1, track the single user who redeemed it
    assigned_to_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)

    # Scope: which modules this code unlocks (null = all tenant-licensed modules)
    modules = Column(JSON, nullable=True)

    # Validity
    expires_at = Column(DateTime(timezone=True), nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)

    # Audit
    created_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    label = Column(String(200), nullable=True)  # Optional batch label, e.g. "Spring 2026 Cohort"

    # Timestamps
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False)
    last_used_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    tenant = relationship("Tenant", back_populates="access_codes")
    assigned_user = relationship("User", foreign_keys=[assigned_to_user_id])
    created_by = relationship("User", foreign_keys=[created_by_user_id])

    def __repr__(self):
        return f"<AccessCode(code='{self.code}', tenant_id={self.tenant_id}, used={self.times_used}/{self.max_uses})>"

    def to_dict(self, include_code: bool = True):
        result = {
            "id": self.id,
            "tenant_id": self.tenant_id,
            "max_uses": self.max_uses,
            "times_used": self.times_used,
            "assigned_to_user_id": self.assigned_to_user_id,
            "modules": self.modules,
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
            "is_active": self.is_active,
            "label": self.label,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "last_used_at": self.last_used_at.isoformat() if self.last_used_at else None,
        }
        if include_code:
            result["code"] = self.code
        return result

    @property
    def is_redeemable(self) -> bool:
        """Check if this code can still be redeemed."""
        if not self.is_active:
            return False
        if self.times_used >= self.max_uses:
            return False
        if self.expires_at and datetime.now(timezone.utc) > self.expires_at:
            return False
        return True
